---
format: html
---

The MEDS program requires all students to have a personal laptop to use during the program. Our curriculum is designed to work across different operating systems and computers, as long as they meet some minimum requirements.  

### Specifically, your computer should:  
- be no more than 4 years old, and in any case be fully supported by the manufacturer. For example, [Apple won't repair anything that's more than 7 years old](https://support.apple.com/en-us/HT201624)   
- be running Windows or macOS ~~or Linux (Please note that we offer limited support for Linux)~~  
- have at least 50 GB storage space available for MEDS applications and coursework  
- have at least 8 GB of RAM (the more the better!)  
- have a 64-bit CPU  

::: {.callout-note}
## Be sure to install the latest operating system

If you already have a laptop that you plan to use in MEDS, be sure to install the latest operating system before the program begins:

- **Mac users:** be sure to update macOS to the newest supported version, as indicated by *System Preferences&rarr;Software Update*. 
- **Windows users:** you should have Windows ~~10 installed but if you don't, you can [purchase Windows 10 Education for $14.99 from UCSB](https://ucsb.onthehub.com/WebStore/OfferingDetails.aspx?o=14f7e678-4731-e511-940e-b8ca3a5db7a1)~~ 11 installed, but if you don't, you can [purchase Windows 11 Education for $XX.XX from UCSB](). 
:::

### If you are purchasing a new computer:

We recommend:

- at least 16 GB of RAM 
- at least 512 GB of SSD (not "disk"!) storage 
- the manucafturer's extended warranty or service plan (e.g., [AppleCare+](https://www.apple.com/support/products/mac/)). 

~~If you are trying to decide between Mac and Windows we would recommend a Mac, but if you purchase or already have a Windows PC, don’t worry that will be just fine as long as it meets our minimum requirements.~~ Choosing between a Mac and Windows machine (aka a PC) can be a personal and / or financial preference. If you're having trouble deciding between the two, we recommend a Mac -- these are popular and user-friendly machines, and the majority of our instructors / staff are Mac users.

You can [purchase a Macbook Air using the higher education discount](https://www.apple.com/us-hed/shop) for \$899 before tax and AppleCare. A PC can cost anywhere from \$500 to more than $3,000; you generally get what you pay for.

### Loaner equipment   

If your computer breaks or dies, we can typically loan you a Windows laptop for up to a month (which should be long enough to have your computer repaired or to purchase a new one).

### Home setup

You may consider having a dedicated computer setup that includes an external monitor, keyboard, and / or mouse at home. A stable at-home WiFi connection is necessary for completing work remotely (i.e. off-campus). 
