---
title: "MEDS Computing Requirements & Software Installation Guide"
author: 
  - name: UCSB MEDS
    url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science/academics-meds
date-modified: last-modified
format: 
  html:
    theme: meds-website-styles.scss
    mainfont: Nunito
    toc: true
    toc-location: left
    toc-depth: 3
    smooth-scroll: true
---

::: {.center-text .body-text-l}
UNDER CONSTRUCTION
:::

::: {.callout-important}
## TODO: 

- NOTE: I combined both the Mac & Windows installation guides bc the only difference was using `which git` vs `where git` when checking for git in step 4; thoughts on this?
  - also, do we need to say anything about checking to see if Git Bash is installed?
  - any other differences in Mac vs. Windows installations that we should be clearer about?
- check which version of R we want students to have (i added most recent version number to step 1)
- do we even want to suggest that incoming students can have a Linux machine?
- update Windows 10 to 11 (or alternative)? link to windows 10 is broken below and I still need link to purchase Windows 11
- get feedback on language around Mac recommendation (I think we've talked about being clearer in this guide about the program having better support for Mac users)
- where do we want to move the slack resources link (step 11 in installation guide) to (if anywhere) after MEDS website is decommissioned?
:::

Incoming MEDS students should follow the steps detailed in this [software installation guide](#install) *before* summer orientation -- there will be a dedicated troubleshooting session, should you need help completing any of the installations. 

Please carefully read through the [computing requirements & recommendations](#comp-reqs) section before deciding on what computer to purchase / use ahead of MEDS. 

## Installation Guide {#install}

<!-- Select your operating system below for software installation instructions: -->

<!-- ::: {.panel-tabset} -->
<!-- ## {{< fa brands apple >}} Mac -->

{{< include install-guide.qmd >}}

<!-- ## {{< fa brands windows >}} Windows -->

<!-- {{< include windows.qmd >}} -->
<!-- ::: -->

## Computing requirements & recommendations {#comp-reqs}

{{< include comp-reqs.qmd >}}